version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: wablash-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: wablash-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/wablash
      # PENTING: harus sama dipakai saat sign() & verify()
      - JWT_SECRET=super-secret-please-change
      - JWT_EXPIRES_IN=12h
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads/media:/app/uploads/media
      - ./backend/uploads/tmp:/app/uploads/tmp
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      args:
        # Dibake saat build → FE panggil API ke host:3001
        - REACT_APP_API_BASE=http://localhost:3001
    container_name: wablash-frontend
    restart: unless-stopped
    environment:
      # Tidak terbaca saat runtime oleh CRA, tapi aman dibiarkan
      - REACT_APP_API_BASE=http://localhost:3001
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3006:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongo_data:
