services:
  backend:
    image: backend
    container_name: wablast-backend
    ports:
      - "3001:3001"
    restart: always

  frontend:
    image: frontend
    container_name: wablast-frontend
    ports:
      - "3005:3000"
    restart: always
